name: weekly-stats-cron
on:
  schedule:
    - cron: '00 0 * * 1'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://benjamincarlson.io/api/weekly-stats' \
          --header 'Authorization: Bearer ${{ secrets.QUIRREL_TOKEN }}'
